routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/mard', 'HumanController@index');
Route::resource('planets', 'PlanetController');

Route::get('/', function () {
    return view('welcome');
});
Route::get('/choose-forum', 'DevelopersController@index');
Route::get('/dev-forum', 'DevelopersController@devForum')->middleware('isDev')->name('dev-forum');
Route::get('/inp-list', 'AdminController@index');
Route::get('/log-list', 'AdminController@admin')->middleware('isAdmin')->name('log-list');
Route::get('/phones', 'PhoneController@index');
Route::get('/country', 'PhoneController@usersCountry');

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    //
}

app/Country.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    //
}

app/Human.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Human extends Model
{
    //
}

app/Phone.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Phone extends Model
{
    //
}

app/Planet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Planet extends Model
{
    protected $fillable = ['name', 'size', 'cordinate'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    public function phones(){
        return $this->hasMany('App\Phone');
    }
    public function countries(){
        return $this->belongsToMany('App\Country');
    }
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AdminController extends Controller
{
    public function index(){
        return view('log');
    }
    public function Admin(Request $request){
        $name = $request->name;

        return view('end', compact('name'));

    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DevelopersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DevelopersController extends Controller
{
    public function index(){
        return view('choose-forum');
}
public function devForum (Request $request){
        $name = $request->name;
        $lastname = $request->lastname;
        $prof = $request->profession;
        return view('devForum', [
            'name' => $name,
            'lastname' => $lastname,
            'prof' => $prof

        ]);
}
}

app/Http/Controllers/HumanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Human;

class HumanController extends Controller
{
    public function index(){
        $people = Human::all();
        dd($people);
    }
}

app/Http/Controllers/PhoneController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Phone;

class PhoneController extends Controller
{
    public function index(){
        $usersData = User::find(2)->email;

        $phones = User::find(2)->phones;
        foreach ($phones as $phone){
            echo $phone->phone . '<br>';
        }
    }
    public function usersCountry(){
        $ggg = User::find(2);
        foreach ($ggg->countries as $gg){
            echo $gg->name . '<br>';
            echo $gg->location . '<br>';


        }
    }
}

app/Http/Controllers/PlanetController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Planet;

class PlanetController extends Controller
{

    public function index()
    {
        $planets = Planet::all();
        return view('PlanetList', compact('planets'));

    }


    public function create()
    {
        return view('AddPlanet');
    }


    public function store(Request $request)
    {
       $input =  $request->except('_token');
       $new_planet  = new Planet();
       $new_planet->fill($input);

       if($new_planet->save()) {

           return redirect('planets');
       } else {return redirect('back');}
    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $planet = Planet::findOrFail($id);
        return view('PlanetUpdate', compact('planet'));
    }


    public function update(Request $request, $id)
    {
        $inputs = $request->except(['_token_', '_method']);
        $update_planets = Planet::find($id);
        $update_planets->fill($inputs);
        $update_planets->update();


    }


    public function destroy($id)
    {
        $del_planet = Planet::find($id);
        $del_planet->delete();
    }
}

resources/views/AddPlanet.blade.php
<form action="{{route('planets.store')}}" method="post">
    @csrf
    <input type="text" name="name"><br>
    <input type="text" name="size">
    <input type="text" name="cordinate">

    <input type="submit">

</form>

resources/views/PlanetList.blade.php
<h1>Planets</h1>
<h2><a href="{{route('planets.create')}}">Add new planet</a></h2>

@foreach ($planets as $planet)
    <p>{{$planet['id']}} {{$planet['name']}}</p>
    <a href="{{route('planets.edit', ['id'=>$planet->id])}}">Edit</a>
    <form action="{{route('planets.destroy', ['id'=>$planet->id])}}" method="post">
        {{@csrf_field()}}
        <input type="hidden" name="_method" value="DELETE">
        <button type="submit">
            DELETE
        </button>
    </form>
@endforeach

resources/views/PlanetUpdate.blade.php
<form action="{{ route('planets.update', ['id'=>$planet->id]) }}" method="post">
    {{@csrf_field()}}
    {{@method_field('PUT')}}
    <div>
        <label>Update Planets</label>
        <input type="text" name="name" value="{{$planet->name}}">
        <input type="text" name="size" value="{{$planet->size}}">
        <input type="text" name="cordinate" value="{{$planet->cordinate}}">

    </div>
    <button type="submit">
        Update Planet
    </button>
</form>

resources/views/choose-forum.blade.php
</form><form action="{{route('dev-forum')}}" method="get">
    <input type="text" name="name"><br><br>
    <input type="text" name="lastname"><br><br>
    <input type="text" name="profession"><br><br>
    <input type="submit">
</form>

resources/views/devForum.blade.php
<p>{{$name}}</p>
<p>{{$lastname}}</p>
<p>{{$prof}}</p>

resources/views/end.blade.php
<p>Hello {{$name}} axper</p>

resources/views/log.blade.php
<form action="{{route('log-list')}}" method="get">
    <input type="text" name="name">
    <input type="email" name="email">
    <input type="submit">
</form>